### ISSUE TITLE
Calendar crashes if there are no date details loaded

### ISSUE THREAD

**Issue by michalbednarski** [MADWI/AppWIZUT2#11]
1. Open calendar without network
2. Click on event 

```
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
            at pl.edu.zut.mad.appwizut2.fragments.CaldroidCustomFragment$1.onSelectDate(CaldroidCustomFragment.java:232)
            at com.roomorama.caldroid.CaldroidFragment$1.onItemClick(CaldroidFragment.java:974)
            at android.widget.AdapterView.performItemClick(AdapterView.java:310)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3042)
            at android.widget.AbsListView$3.run(AbsListView.java:3879)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by michalbednarski** [comment]
Actually, this happens even when there is network connection, however it won't happen after manually refreshing list of events in calendar (Pulling down on events list).
