### ISSUE TITLE
Crash when bus timetable data are loaded after activity destroy

### ISSUE THREAD

**Issue by michalbednarski** [MADWI/AppWIZUT2#5]
```
12-01 10:47:59.476  12890-12890/pl.edu.zut.mad.appwizut2 E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: pl.edu.zut.mad.appwizut2, PID: 12890
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
            at android.widget.SimpleAdapter.<init>(SimpleAdapter.java:93)
            at pl.edu.zut.mad.appwizut2.utils.BusTimetable$GetTimetables.onPostExecute(BusTimetable.java:214)
            at pl.edu.zut.mad.appwizut2.utils.BusTimetable$GetTimetables.onPostExecute(BusTimetable.java:73)
            at android.os.AsyncTask.finish(AsyncTask.java:651)
            at android.os.AsyncTask.-wrap1(AsyncTask.java)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by dmcyk** [comment]
fixed with the latest commit of OfflineData, test and confirm please

**Comment by michalbednarski** [comment]
Not sure if this should be counted as new issue, but now it crashes if you rotate device during load

```
12-13 14:59:12.984 12801-12801/pl.edu.zut.mad.appwizut2 D/AndroidRuntime: Shutting down VM


                                                                          --------- beginning of crash
12-13 14:59:12.985 12801-12801/pl.edu.zut.mad.appwizut2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: pl.edu.zut.mad.appwizut2, PID: 12801
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{pl.edu.zut.mad.appwizut2/pl.edu.zut.mad.appwizut2.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                              at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
                                                                              at android.app.ActivityThread.-wrap15(ActivityThread.java)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                           Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
                                                                              at android.widget.SimpleAdapter.getCount(SimpleAdapter.java:100)
                                                                              at android.widget.ListView.setAdapter(ListView.java:491)
                                                                              at android.support.v4.app.ListFragment.setListAdapter(ListFragment.java:182)
                                                                              at pl.edu.zut.mad.appwizut2.utils.BusTimetable.onViewCreated(BusTimetable.java:121)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1097)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
                                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1241)
                                                                              at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2053)
                                                                              at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:165)
                                                                              at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:543)
                                                                              at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                              at android.app.Activity.performStart(Activity.java:6268)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                              at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077) 
                                                                              at android.app.ActivityThread.-wrap15(ActivityThread.java) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:148) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```
